<?php
define("PRESET_TEXT_NAME","preset_text_name");
define("PRESET_TEXT_POST","preset_text_post");
define("PRESET_TEXT_TEL","preset_text_tel");
define("PRESET_TEXT_NAME?FURIGANA","preset_text_name_furigana");
define("PRESET_SELECT_PREF","preset_select_pref");
define("PRESET_SELECT_BIRTHDAY","preset_select_birthday");
define("PRESET_SELECT_YEAR_MONTH","preset_select_year_month");
define("PRESET_SELECT_MONTH_DAY","preset_select_month_day");
define("PRESET_TEXT_ADDRESS","preset_text_address");
define("PRESET_RADIO_BOX","preset_radio_box");
define("PRESET_TEXT_MAIL","preset_text_mail");
?>
